server:
  # Force Prometheus to run in eu-west-1a (same AZ as the NLB static IP)
  nodeSelector:
    topology.kubernetes.io/zone: eu-west-1a
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      # Set a static private IP address for the load balancer, that will persist across reboots for Grafana to connect to!
      service.beta.kubernetes.io/aws-load-balancer-private-ipv4-addresses: "10.0.4.200"
      service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0fea78d9788180ab5"
  persistentVolume:
    enabled: false

alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false

# This will now find all the pods in the xtdb-deployment namespace that are labelled with 'xtdb-statefulset-$' and scrape them on port 8080 (healthz)
extraScrapeConfigs: |
  - job_name: 'xtdb'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: ['xtdb-deployment']
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: xtdb-statefulset
        action: keep
      - source_labels: [__address__]
        regex: ([^:]+)(?::\d+)?
        replacement: $1:8080
        target_label: __address__
