# Production environment overrides
# Usage: helm upgrade xtdb ./helm -f values.yaml -f values-prod.yaml

nodeCount: 3

xtdbConfig:
  jdkOptions: >-
    -Dkotlinx.coroutines.debug=on
    -XX:+UseG1GC
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:HeapDumpPath=/var/lib/xtdb/
    -Xmx5G
    -Xms2G
    -XX:MaxDirectMemorySize=2G
    -Dclojure.server.repl="{:port 7888 :accept clojure.core.server/repl}"
#  jdkOptions: "-Dlog4j2.debug=true -Dkotlinx.coroutines.debug=on -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/lib/xtdb/ -Xmx5G -Xms2G -Dclojure.server.repl=\"{:port 7888 :accept clojure.core.server/repl}\""
#  jdkOptions: "-Dkotlinx.coroutines.stacktrace.recovery=true -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/lib/xtdb/ -Xmx5G -Xms2G -Dclojure.server.repl=\"{:port 7888 :accept clojure.core.server/repl}\""
#  jdkOptions: "-agentpath:/opt/yourkit/libyjpagent.so=port=10001,listen=all -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/lib/xtdb/ -Xmx5G -Xms2G -Dclojure.server.repl=\"{:port 7888 :accept clojure.core.server/repl}\""
#  jdkOptions: "-Xmx3G -Xms3G -XX:MaxDirectMemorySize=3G -XX:MaxMetaspaceSize=500m -Dio.netty.maxDirectMemory=1073741824 -Dclojure.server.repl=\"{:port 7888 :accept clojure.core.server/repl}\""

  localDiskCache:
    sizeLimit: "35Gi"

  env:
    XTDB_LOG_FORMAT: json

#    XTDB_LOG_JSON_TEMPLATE: classpath:xtdb/logging/AzureMonitorLayout.json
#    XTDB_LOGGING_LEVEL_metrics: "debug"
#    XTDB_LOG_LEVEL_xtdb_metrics: "debug"
#    XTDB_LOG_LEVEL_xtdb_aws_S3: "trace"
#    XTDB_LOG_LEVEL_xtdb_pgwire: "debug"
#    XTDB_LOG_LEVEL_xtdb_compactor: "debug"
#    XTDB_LOG_LEVEL_xtdb_segment: "debug"
#    XTDB_LOG_LEVEL_xtdb_metadata: "debug"
    XTDB_LOGGER_LEVEL_xtdb_garbage__collector: debug
#    XTDB_LOGGER_LEVEL_software_amazon_awssdk: debug
    XTDB_LOGGING_LEVEL: info
#    XTDB_LOGGING_LEVEL_AWS: "trace"
    XTDB_LOGGING_LEVEL_INDEXER: debug
#    XTDB_LOGGING_LEVEL_PGWIRE: "trace"

startupProbe:
  httpGet:
    path: /healthz/started
    port: 8080
  # 2 minute initial delay to allow XTDB system to startup before awaiting index catchup
  initialDelaySeconds: 120
  # Allow up to fifteen minutes for catchup of initial indexes, checking every 15 seconds
  periodSeconds: 15
  failureThreshold: 60

# The liveness (and readiness) probes are disabled by Kubernetes until the startup probe has succeeded.
livenessProbe:
  httpGet:
    path: /healthz/alive
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 6
  timeoutSeconds: 5
