apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: xtdb-pod-restart
  namespace: chaos-mesh
spec:
  schedule: "@every 10m"
  type: PodChaos
  podChaos:
    action: pod-kill
    mode: one
    selector:
      namespaces:
        - xtdb-deployment
      labelSelectors:
        app: xtdb-statefulset