synthea-feeder:
  population: 2
  interval-seconds: 10

logging:
  level:
#    org.springframework.beans: DEBUG
    io.awspring.cloud.paramstore: DEBUG
    org.springframework.cloud.aws: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/xtdb
    username: xtdb
    password: xtdb
    hikari:
      maximum-pool-size: 10

  jmx:
    enabled: true

  cloud:
    aws:
      parameterstore:
        enabled: true  # Disable for local dev

management:
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: refresh
